use std::fs::File;
use std::io;
use std::io::Write;

fn main() {
    let woman_names = vec![
        "Marie",
        "Jana",
        "Eva",
        "Anna",
        "Hana",
        "Vera",
        "Lenka",
        "Alena",
        "Jaroslava",
        "Olga",
        "Milada",
        "Andrea",
        "Iveta",
        "Pavlina",
        "Sarka",
        "Zdenka",
        "Blanka",
        "Nikola",
        "Renata",
        "Gabriela",
        "Milena",
        "Simona",
        "Radka",
        "Iva",
        "Denisa",
        "Daniela",
        "Kvetoslava",
        "Lucie",
        "Petra",
        "Katerina",
        "Ludmila",
        "Jitka",
        "Jarmila",
        "Veronika",
        "Martina",
        "Jirina",
        "Michaela",
        "Tereza",
        "Monika",
        "Zuzana",
        "Marketa",
        "Marcela",
        "Dagmar",
        "Ruzena",
        "Marta",
        "Barbora",
        "Miroslava",
        "Eliska",
        "Irena",
        "Pavla",
        "Kristyna",
    ];
    let woman_surnames = vec![
        "Novakova",
        "Svobodova",
        "Novotna",
        "Dvorakova",
        "Kralova",
        "Cerna",
        "Prochazkova",
        "Prochazkova",
        "Kovarova",
        "Kucerova",
        "Vesela",
        "Horakova",
        "Markova",
        "Pokorna",
        "Pospisilova",
        "Hajkova",
        "Kralova",
        "Jelinkova",
        "Ruzickova",
        "Benesova",
        "Fialova",
        "Sedlackova",
        "Dolezalova",
        "Zemanova",
        "Kolarova",
        "Navratilova",
        "Cermakova",
        "Vankova",
        "Urbanova",
        "Kratochvilova",
        "Simkova",
        "Blazkova",
        "Krizova",
        "Kopecka",
        "Bartosova",
        "Vlckova",
        "Polakova",
        "Konecna",
        "Musilova",
        "Cechova",
        "Mala",
        "Stankova",
        "Stepankova",
        "Holubova",
        "Kadlecova",
        "Stastna",
        "Dostalova",
        "Soukupova",
        "Maresova",
        "Valentova",
        "Moravcova",
        "Krejcova",
        "Pavlikova",
        "Jandova",
        "Hruskova",
        "Havlickova",
        "Hruska",
        "Hruba",
        "Havlicek",
        "Janda",
        "Liskova",
        "Tomanova",
        "Vackova",
        "Bednarova",
    ];

    let man_names = vec![
        "Jiri",
        "Frantisek",
        "Josef",
        "Stepan",
        "Vaclav",
        "Michal",
        "Helena",
        "Ladislav",
        "Stanislav",
        "Karel",
        "Milan",
        "Vladimir",
        "David",
        "Lukas",
        "Jakub",
        "Jaroslav",
        "Martin",
        "Roman",
        "Libuse",
        "Marek",
        "Daniel",
        "Tomas",
        "Miroslav",
        "Jan",
        "Petr",
        "Pavel",
        "Miloslav",
        "Vojtech",
        "Rudolf",
        "Milos",
        "Adam",
        "Lubomir",
        "Patrik",
        "Bohumil",
        "Dominik",
        "Lubos",
        "Robert",
        "Jindrich",
        "Filip",
        "Jaromir",
        "Ivan",
        "Ales",
        "Oldrich",
        "Libor",
        "Ondrej",
        "Radek",
    ];
    let man_surnames = vec![
        "Novak",
        "Svoboda",
        "Novotny",
        "Dvorak",
        "Cerny",
        "Prochazka",
        "Kucera",
        "Vesely",
        "Krejci",
        "Horak",
        "Nemcova",
        "Nemec",
        "Ruzicka",
        "Marek",
        "Fiala",
        "Pospisil",
        "Pokorny",
        "Hajek",
        "Kral",
        "Jelinek",
        "Benes",
        "Sedlacek",
        "Dolezal",
        "Zeman",
        "Navratil",
        "Cermak",
        "Vanek",
        "Kolar",
        "Urban",
        "Blazek",
        "Kriz",
        "Kovar",
        "Kratochvil",
        "Bartos",
        "Vlcek",
        "Polak",
        "Musil",
        "Kopecky",
        "Simek",
        "Konecny",
        "Maly",
        "Holub",
        "Cech",
        "Stepanek",
        "Stanek",
        "Kadlec",
        "Dostal",
        "Soukup",
        "Stastny",
        "Mares",
        "Aevcik",
        "Masek",
        "Dusek",
        "Pavlik",
        "Hruby",
        "Mach",
    ];

    let mut write_domain = String::new();
    println!("Enter your domain :");

    let _user_domain = io::stdin().read_line(&mut write_domain).unwrap();
    let mut file = File::create("email.txt").expect("Error!");
    let mut woman_full_names = Vec::with_capacity(woman_names.len() * woman_surnames.len());
    for name in &woman_names {
        for surname in &woman_surnames {
            woman_full_names.push(format!("{}.{}@{}", name, surname, write_domain));
        }
    }
    let mut man_full_names = Vec::with_capacity(man_names.len() * man_surnames.len());
    for name in &man_names {
        for surname in &man_surnames {
            man_full_names.push(format!("{}.{}@{}", name, surname, write_domain));
        }
    }

    for names in man_full_names {
        file.write_all(names.as_bytes()).expect("Write error!");
    }
    for names in woman_full_names {
        file.write_all(names.as_bytes()).expect("Write error!");
    }
}
